---
baseURL: http://blog.oddbit.com/
languageCode: en-us
title: The Odd Bit
theme: ghostwriter
enableGitInfo: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: false
pygmentsUseClasses: true

outputs:
  home:
    - HTML
    - RSS
    - Atom
  taxonomy:
    - HTML
    - RSS
    - Atom
  taxonomyTerm:
    - HTML
    - RSS
    - Atom

mediaTypes:
  application/rss+xml:
    suffixes:
      - xml
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "rss"
  Atom:
    mediatype: "application/atom+xml"
    baseName: "atom"

ignorefiles:
  - content/scripts
  - content/ci

params:
  description: One of these things is not like the others
  twitter: 'https://twitter.com/larsks'
  github: 'https://github.com/larsks'
  stackoverflow: "https://stackoverflow.com/users/147356/larsks"
  shareFacebook: false
  shareGooglePlus: false
  showSummary: true
  showMore: true


author:
  name: Lars Kellogg-Stedman
  profile: /about/lars

permalinks:
  posts: '/post/:year/:month/:title/'
  tags: '/tag/:slug/'

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Tags
      url: /tags
      weight: 2
    - name: GPG Key
      url: /about/gpg/
      weight: 3
    - name: Answers
      url: /about/stackoverflow/
      weight: 3
