---
baseURL: /
languageCode: en-us
title: The Odd Bit
theme: ghostwriter
enableGitInfo: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: false
pygmentsUseClasses: true

staticDir:
  - static
  - content/static

outputs:
  home:
    - HTML
    - RSS
    - Atom
  taxonomy:
    - HTML
    - RSS
    - Atom
  taxonomyTerm:
    - HTML
    - RSS
    - Atom

mediaTypes:
  application/rss+xml:
    suffixes:
      - xml
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  RSS:
    mediatype: "application/rss+xml"
    baseName: "rss"
  Atom:
    mediatype: "application/atom+xml"
    baseName: "atom"

ignorefiles:
  - content/scripts
  - content/static

params:
  description: One of these things is not like the others
  twitter: 'https://twitter.com/larsks'
  github: 'https://github.com/larsks'

author:
  name: Lars Kellogg-Stedman
  profile: /about/lars

permalinks:
  posts: '/post/:year/:month/:title/'

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /post
      weight: 2
    - name: Tags
      url: /tags
      weight: 2
    - name: GPG Key
      url: /about/gpg
      weight: 2
