#!/usr/bin/ansible-playbook

---
- hosts: localhost
  gather_facts: false
  vars:
    ghp_remote: publish
    ghp_branch: gh-pages
  tasks:
    - name: ensure gh-pages is up to date
      command: >-
        git remote update {{ ghp_remote }}

    - name: publish content to github
      tags: [publish]
      command: >-
        ghp-import -p -n
        -m "Publish blog to {{ ghp_remote }}:{{ ghp_branch }}"
        -r {{ ghp_remote }}
        -b {{ ghp_branch }}
        -f
        public/
