#!/usr/bin/ansible-playbook

---
- hosts: localhost
  gather_facts: false
  vars:
    hugo_env: production
    hugo_content_directory: content
  tasks:
    - name: get current date
      command: >-
        date '+%Y-%m-%dT%H:%M:%SZ'
      environment:
        TZ: UTC
      register: date

    - name: get HEAD commit id from content
      command: git rev-parse HEAD
      args:
        chdir: "{{ hugo_content_directory }}"
      register: content

    - name: get HEAD commit id from config
      command: git rev-parse HEAD
      register: config

    - name: remove old rendered content
      file:
        path: public
        state: absent

    - name: render content
      command: >-
        hugo -v -e {{ hugo_env }} -c {{ hugo_content_directory }}

    - name: create metadata variable
      set_fact:
        metadata:
          content: "{{ content.stdout }}"
          config: "{{ config.stdout }}"
          date: "{{ date.stdout }}"

    - name: add metadata to published content
      copy:
        dest: public/metadata.json
        content: "{{ metadata|to_nice_json }}"
