#!/usr/bin/ansible-playbook

---
- hosts: localhost
  gather_facts: false
  vars:
    hugo_env: production
    hugo_content_directory: content
  tasks:
    - name: get current date
      command: >-
        date '+%Y-%m-%dT%H:%M:%SZ'
      environment:
        TZ: UTC
      register: date

    - name: get HEAD commit id from content
      command: git rev-parse HEAD
      args:
        chdir: "{{ hugo_content_directory }}"
      register: content

    - name: get HEAD commit id from config
      command: git rev-parse HEAD
      register: config

    - name: get list of submodules
      command: git config --blob HEAD:.gitmodules --list
      register: submodules_cmd

    - name: parse list of submodules
      set_fact:
        submodules: "{{ submodules|default([]) + [item.split('=')[1]] }}"
      when: "'.path=' in item"
      loop: "{{ submodules_cmd.stdout_lines }}"

    - name: get submodule commit ids
      command: git -C {{ item }} rev-parse HEAD
      loop: "{{ submodules }}"
      register: commits

    - set_fact:
        submodule_commits: >-
          {{ submodule_commits|default({})|
          combine({item.item: item.stdout}) }}
      loop: "{{ commits.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: remove old rendered content
      file:
        path: public
        state: absent

    - name: render content
      command: >-
        hugo -v -e {{ hugo_env }} -c {{ hugo_content_directory }}

    - name: create metadata variable
      set_fact:
        metadata:
          date: "{{ date.stdout }}"
          content: "{{ content.stdout }}"
          config: "{{ config.stdout }}"
          submodules: "{{ submodule_commits }}"

    - name: add metadata to published content
      copy:
        dest: public/metadata.json
        content: "{{ metadata|to_nice_json }}"
